name: Deploy Notebook to Databricks Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 🧰 Install Databricks CLI
        run: pip install databricks-cli

      - name: 🔐 Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databricks/config
[DEFAULT]
host = ${{ secrets.DATABRICKS_DEV_HOST }}
token = ${{ secrets.DATABRICKS_DEV_TOKEN }}
EOF

      - name: 🚀 Upload notebook to Databricks Dev
        run: |
          echo "Uploading notebooks/hello_world.py to /Repos/CI-CD/hello_world_dev.py"
          databricks workspace import \
            notebooks/hello_world.py \
            /Repos/CI-CD/hello_world_dev.py \
            --language PYTHON \
            --overwrite

      - name: ✅ Deployment complete
        run: echo "Notebook successfully deployed to Databricks Dev!"
